# Generated by Django 6.0.3 on 2026-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousrequest',
            name='reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('bullying', 'Буллинг'), ('conflict', 'Конфликт'), ('anxiety', 'Тревога'), ('family', 'Семейные проблемы'), ('study', 'Проблемы с учёбой'), ('other', 'Другое')], default='', max_length=20, verbose_name='Причина обращения'),
        ),
        migrations.AddField(
            model_name='emotionentry',
            name='event_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('bullying', 'Буллинг'), ('conflict', 'Семейный конфликт'), ('study', 'Стресс от учёбы'), ('loneliness', 'Одиночество'), ('other', 'Другое')], default='', max_length=20, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='emotionentry',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Жақсы / Хорошо'), ('calm', 'Тыныш / Спокойно'), ('anxious', 'Алаңдаулы / Тревожно'), ('sad', 'Қайғылы / Грустно'), ('angry', 'Ашулы / Злой'), ('tired', 'Шаршаулы / Устал')], max_length=20),
        ),
    ]
