# Generated by Django 6.0.3 on 2026-04-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_anonymousrequest_reason_emotionentry_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(choices=[('manual', 'Конструктор'), ('ai', 'ИИ генерация')], default='manual', max_length=10)),
                ('topic', models.CharField(choices=[('anxiety', 'Тревожность'), ('depression', 'Депрессия'), ('stress', 'Стресс'), ('selfesteem', 'Самооценка'), ('relations', 'Отношения'), ('bullying', 'Буллинг'), ('motivation', 'Мотивация'), ('other', 'Другое')], default='anxiety', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_tests', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Психологический тест',
                'verbose_name_plural': 'Психологические тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PsychTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('q_type', models.CharField(choices=[('radio', 'Один вариант'), ('checkbox', 'Несколько вариантов'), ('scale', 'Шкала 1-5'), ('text', 'Открытый ответ')], default='radio', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты ответов')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес вопроса')),
                ('order', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.psychtest')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PsychTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10)),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Анализ ИИ')),
                ('psy_conclusion', models.TextField(blank=True, verbose_name='Заключение психолога')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждено')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.psychtest')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
                'unique_together': {('test', 'student')},
            },
        ),
    ]
