# Generated by Django 6.0.3 on 2026-04-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_psychtest_psychtestquestion_psychtestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('appointment_new', 'Новая заявка на приём'), ('appointment_confirmed', 'Запись подтверждена'), ('appointment_rejected', 'Запись отклонена'), ('anonymous_new', 'Новый анонимный запрос'), ('request_new', 'Новая жалоба ученика'), ('request_ai_ready', 'ИИ-анализ готов'), ('request_concluded', 'Психолог вынес заключение'), ('observation_new', 'Новый сигнал от учителя'), ('parent_conclusion', 'Заключение для родителя')], max_length=30),
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('anxiety', 'Тревога / Стресс'), ('bullying', 'Буллинг'), ('family', 'Семейные проблемы'), ('study', 'Проблемы с учёбой'), ('behavior', 'Поведение'), ('relations', 'Отношения в классе'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Психолог видит класс и возраст, но не имя', verbose_name='Скрыть имя от психолога')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('ai_analyzed', 'ИИ проанализировал'), ('in_review', 'На рассмотрении'), ('concluded', 'Заключение готово'), ('archived', 'Архив')], default='new', max_length=20, verbose_name='Статус')),
                ('lang', models.CharField(default='ru', max_length=5, verbose_name='Язык обращения')),
                ('ai_tone', models.CharField(blank=True, choices=[('neutral', 'Нейтральная'), ('anxiety', 'Тревожность'), ('depression', 'Подавленность'), ('aggression', 'Агрессия'), ('fear', 'Страх'), ('confusion', 'Растерянность')], default='', max_length=20, verbose_name='Тональность (ИИ)')),
                ('ai_risk_level', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='', max_length=10, verbose_name='Уровень риска (ИИ)')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Резюме для психолога (ИИ)')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='Список ключевых сигналов, например ["буллинг","изоляция"]', verbose_name='Теги ИИ')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время анализа ИИ')),
                ('psy_risk_override', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='', help_text='Если пусто — используется оценка ИИ', max_length=10, verbose_name='Уровень риска (психолог)')),
                ('psy_conclusion', models.TextField(blank=True, verbose_name='Заключение психолога')),
                ('psy_recommendations', models.TextField(blank=True, verbose_name='Рекомендации психолога')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Заключение утверждено')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время утверждения')),
                ('parent_message', models.TextField(blank=True, help_text='Эмпатичная версия заключения, сформированная ИИ или психологом', verbose_name='Сообщение для родителя')),
                ('parent_notified', models.BooleanField(default=False, verbose_name='Родитель уведомлён')),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Время уведомления родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначен психолог')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Жалоба ученика',
                'verbose_name_plural': 'Жалобы учеников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('withdrawal', 'Замкнутость / изоляция'), ('aggression', 'Агрессивное поведение'), ('mood_drop', 'Резкая смена настроения'), ('academic_decline', 'Резкое снижение успеваемости'), ('absence', 'Частые пропуски'), ('anxiety_signs', 'Признаки тревоги / страха'), ('peer_conflict', 'Конфликт с одноклассниками'), ('self_harm_risk', 'Признаки самоповреждения'), ('other', 'Другое')], default='other', max_length=25, verbose_name='Тип наблюдения')),
                ('urgency', models.CharField(choices=[('low', 'Низкая — для наблюдения'), ('medium', 'Средняя — требует внимания'), ('high', 'Высокая — нужна реакция'), ('critical', 'Критическая — немедленно')], default='low', max_length=10, verbose_name='Срочность')),
                ('description', models.TextField(help_text='Что именно изменилось в поведении, когда началось, контекст', verbose_name='Описание наблюдения')),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, help_text='Сколько дней наблюдается изменение поведения', null=True, verbose_name='Продолжительность (дней)')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Просмотрено психологом')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время просмотра')),
                ('psy_note', models.TextField(blank=True, verbose_name='Заметка психолога по сигналу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_observations', to='core.studentrequest', verbose_name='Связанная жалоба')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_observations', to=settings.AUTH_USER_MODEL, verbose_name='Просмотрел психолог')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_observations', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Наблюдение учителя',
                'verbose_name_plural': 'Наблюдения учителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
